git config --global alias.a 'add'
git config --global alias.as '!git config -l | grep alias'
git config --global alias.c 'commit'
git config --global alias.s 'status'
git config --global alias.h '!git log -1 --format="%H"'
